CPR to TARGA convertor, to preserve exact palette order and values (or end*.cpr look ok, but text on them printed by the game is broken) Updates: https://github.com/mnalis/ironseed_fpc/issues/59

diff --git a/Data_Generators/misc/pngpal_to_cpr b/Data_Generators/misc/pngpal_to_cpr
--- a/Data_Generators/misc/pngpal_to_cpr
+++ b/Data_Generators/misc/pngpal_to_cpr
@@ -7,10 +7,13 @@ PATH="$PATH:`dirname $0`"
 PNGSRC="$1"
 PALSRC="$2"
 EMBED_PAL="$3"
+UPDATE="$4"
+
 if [ -z "$PNGSRC" -o -z "$PALSRC"  -o -z "$EMBED_PAL" ]
 then
-	echo "Usage: $0 <Graphic_Assets/SOMETHING.png> <data/main.pal> <embed_pal=0/1>"
+	echo "Usage: $0 <Graphic_Assets/SOMETHING.png> <data/main.pal> <0|1> [UPDATE]"
 	echo "Converts SOMETHING.png using main.pal to $TEMPDIR/SOMETHING.cpr"
+	echo "0|1 is for embedded PAL (CPR flag), and UPDATE if we are using partial PAL file"
 	exit 11
 fi
 
@@ -34,15 +37,24 @@ CPR="$TMPBASE.cpr"
 TMPPPM="$TMPBASE.ppm"
 TMPPAL="$TMPBASE.pal"
 
-echo "Converting $PNGSRC + $PALSRC to $CPR (EMBED_PAL=$EMBED_PAL WIDTH=$WIDTH HEIGHT=$HEIGHT)"
+echo "Converting $PNGSRC + $PALSRC to $CPR (EMBED_PAL=$EMBED_PAL WIDTH=$WIDTH HEIGHT=$HEIGHT UPDATE=$UPDATE)"
+
+if [ `stat --format=%s $PALSRC` -ge 768 -a "$UPDATE" = "UPDATE" ]
+then
+	echo "ERROR: UPDATE specified, but PAL $PALSRC size already full"
+	exit 21
+fi
+
 
 convert "$PNGSRC" "$TMPPPM" || exit 14
 cp -f "$PALSRC" "$TMPPAL" || exit 15
 
 export WIDTH
 export HEIGHT
-ppmpal2scr.pl "$TMPPPM" "$TMPPAL" || exit 16
-scr2cpr "$TMPBASE" $EMBED_PAL $WIDTH $HEIGHT
+
+
+ppmpal2scr.pl "$TMPPPM" "$TMPPAL" $UPDATE || exit 16
+scr2cpr "$TMPBASE" $EMBED_PAL $WIDTH $HEIGHT || exit 17
 
 rm -f "$TMPPPM" "$TMPPAL" "$TMPBASE.scr"
 exit 0
